apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: treetracker-database-connection
  namespace: bulk-pack-services
spec:
  encryptedData:
    db: AgDFG1Jhg8jAhBNDc5+gG46aV7G1X79BOoWr9yF1uzjyZI6BCRcpWe9NamnWwjPVuMTo9j0sqybRD6pCwQYyQNP04JyRFNgg/7fALciftdnncuuKMMXh6ZlVt1wmEajhJipoelRu9axlHAAEPk2a72rRiR8omhoAr1dA84VLBEX2bDhOWrU5oa/Yt/0dE6oWHUCJa8LQlnVOTTcjD88H9xU22QaoCuGNErvvsbingSxrxIeYh1t5ZclNzK/m46k45maINl0AKmgRxUzZq1y/fdsfi10lE8lQhriGCXPVWBladTOfUhwhP80Pv8EjSTvqDEha8Ajb6d6xbgs2U7hZCVoyD36GNNAybmWXG6RoO91gdn8DQCb5lwnSMjxe0PHIC5bbOXpgQWdML+TiUA3TMld6w8CppalrUSItqHxRpbZGG1clEh6Chei9L2GMmb+WwGex7ab4uRgeVdf0vnB9TUrVB49ruq1Ag51QUFXGNNskXYXEDEO4duqG01W+jv1QEFL6uej9mfp+wQw+Qdx70TVkVp9WPOos5mxafGOa7NiAOOmK/33/eXuVB6w7BuIZGz41Ncv1vSndjACK/lt2k3crfFku1d/4qPO2sMvBEugvolPkjFLUDbkcEgIBpxTemS28H/vgUnjOYMm10GGLW5539vZm3xuPFE1AygRXiopK997+7b50Cg1Z8/HTL+uApXewaSmW3QK/QCEHsk5AmHOloTLyWq/wu+wqcTZ758m3pk4x9jXO02mtRThn+sTTXk1mPzBv7n8w96bbwAbryb0VDpFOVrwmgAS8h6mtRcMnmlJ8UR6UEww1LZiLWIhpgntAlOtpemd9PfDaVsM9l5qd5UdxU7zM+fIyqfWREs/h39p8
  template:
    metadata:
      creationTimestamp: null
      name: treetracker-database-connection
      namespace: bulk-pack-services

