apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: treetracker-database-connection
  namespace: bulk-pack-services
spec:
  encryptedData:
    db: AgCI2EOHM6OLxlDKz+hWHOL4aTUa+0mV+ndVDtCPWkJgPIjbj6iNQ9Lu5vtW3IuHe8TRmbzuJfLEXOskfD4b9rLrEdi+mH/bTs9sevhBi9qcaPqBpELMCYka8LMX6mbehQI65vs31j/l9Ap3Q2d5J1IYVs9KGTiKYv67EPw5BtuyeP4To1xqbPRcNAx8ByOB2xhk5InIhsvPEtWxLx9bNaDKKkL621a+jGGfbV+wtnGTTSvlW06ZgF7ulzckgmxpeLZsPeNBn0+IvPixS4/r54rCRqbSFge5jGuEoGWPtBspoW/HGPt9B+9HWf9OQPe/UR8W6iX7qVkANTjCFnR8EfhfwXDDCdfcFDytB1S5WxXQj8K3aeSiNR76xKIegU/Vivl15Ea9NiybJJTOm1Fc+JwDjm6EPrNli1RnbDUgq+CJ3slrPrMEcLQriUh7nfEPDyhCuQk2RTdgQgiT0Xsh5TLbhpOMj595bboOlId4nckR0tm0bZpJmG42ChgXxRJYswpBtUPlnH8gmUbHAc3QlR9lw4bfTqwkYO4l4EWN4WxAGf8GIoFJfYH7R0mjqsjmNK7O4hYX/5AR2XiftzfEQs9IuFnK4wcmsYEp4ijRLOzC6vwmsd00ni1zyijS3UR4cDdhZWzUh6MXxD/Tq7SOZuFchupi5SgUHYwnf5uQwpz/TFf74pxEhPItblRW0Q3kO724P0HPX6BufRmLmBGWsHKQfsg+3ZgF6kA86+6KRIvJysHCiw3Gnpy3jFx5BGrqPI8ZbGoHYsAu6TCIyDlC7Tq6hU4jSH02lTyBs5UUfJzaURqnbDH8Ak3v7L7PXrw1lwk2hblgPYEDUjD6oe1Io/2q9gJ52YjE+eisFgd4ia7tV8UfT3RhYWbw
  template:
    metadata:
      creationTimestamp: null
      name: treetracker-database-connection
      namespace: bulk-pack-services

