apiVersion: apps/v1
kind: Deployment
metadata:
  name: bulk-pack-transformer
  labels:
    app: bulk-pack-transformer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bulk-pack-transformer
  template:
    metadata:
      labels:
        app: bulk-pack-transformer
    spec:
      containers:
      - name: bulk-pack-former
        image: greenstand/bulk-pack-transformer:latest
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: treetracker-database-connection
                key: db
          - name: FIELD_DATA_URL
            value: "https://dev-k8s.treetracker.org/field-data/"
          - name: USE_FIELD_DATA
            value: "true"
          - name: NODE_LOG_LEVEL
            value: trace
          - name: REMOTE_LOG_URL
            value: http://104.131.78.177:8000
